<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  <OutputType>Exe</OutputType>
  <TargetFramework>net10.0-windows</TargetFramework>
  <UseWindowsForms>true</UseWindowsForms>
  <ImplicitUsings>enable</ImplicitUsings>
  <Nullable>disable</Nullable>
</PropertyGroup>

  <ItemGroup>
    <None Update="assets\Greeting.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Windows.Extensions" Version="10.0.5" />
  </ItemGroup>

</Project>
